import type { IResume } from "~/types";
import {
    Category,
    CategoryDriveLicense,
    City,
    Currency,
    EducationLevel,
    EmploymentType,
    WorkExperience,
    WorkSchedule
} from "~/types";

const data: IResume[] = [
    {
        id: 1,
        title: "Frontend бағдарламашы",
        slug: "frontend-developer",
        from_salary: 2000,
        to_salary: 3000,
        currency: Currency.USD,
        work_experience: WorkExperience.ONE_TO_THREE_YEARS,
        date_publish: "2025-01-18",
        avatar: "mdi-account-circle-outline",
        education_level: EducationLevel.HIGHER,
        category: Category.IT,
        info_resume: {
            conditions: [EmploymentType.FULL_TIME, WorkSchedule.REMOTE],
            removal: true,
            business_trip: false,
            gender: "MAN",
            age: 25,
            city: City.ALMATY,
            work_experience: [
                {
                    date_from: "2023-01-01",
                    date_to: "2024-12-31",
                    title: "Junior Frontend Developer",
                    category: Category.IT,
                    company: "Tech Solutions",
                    desc_experience: "Vue.js және TypeScript арқылы интерфейстер әзірлеу.",
                },
            ],
            education: [
                {
                    date_from: "2020-09-01",
                    place: "Қазақ ұлттық университеті",
                    professional: "Ақпараттық технологиялар",
                },
            ],
            professional_skills: ["HTML", "CSS", "JavaScript", "Vue.js"],
            personal_skills: "Қарым-қатынас, жауапкершілік, шығармашылық.",
            lang: ["Қазақша", "Ағылшынша"],
            category_drive_license: [CategoryDriveLicense.B],
        },
    },
    {
        id: 2,
        title: "Сату менеджері",
        slug: "sales-manager",
        from_salary: 350000,
        to_salary: null,
        currency: Currency.KZT,
        work_experience: WorkExperience.NO_EXPERIENCE,
        date_publish: "2025-01-17",
        avatar: "mdi-account-circle-outline",
        education_level: EducationLevel.SECONDARY,
        category: Category.SALES,
        info_resume: {
            conditions: [EmploymentType.PART_TIME],
            removal: false,
            business_trip: false,
            gender: "WOMEN",
            age: 22,
            city: City.ASTANA,
            work_experience: [],
            education: [
                {
                    date_from: "2019-09-01",
                    place: "Экономика және қызмет колледжі",
                    professional: "Менеджмент",
                },
            ],
            professional_skills: ["Сату дағдылары", "Келіссөздер", "Клиенттермен жұмыс"],
            personal_skills: "Қарым-қатынас, мақсатқа ұмтылушылық, икемділік.",
            lang: ["Қазақша"],
            category_drive_license: [],
        },
    },
    {
        id: 3,
        title: "Жүк көлігінің жүргізушісі",
        slug: "truck-driver",
        from_salary: 70000,
        to_salary: 100000,
        currency: Currency.RUB,
        work_experience: WorkExperience.THREE_TO_FIVE_YEARS,
        date_publish: "2025-01-16",
        avatar: "mdi-account-circle-outline",
        education_level: EducationLevel.SECONDARY,
        category: Category.TRANSPORT,
        info_resume: {
            conditions: [EmploymentType.TEMPORARY, WorkSchedule.ROTATIONAL],
            removal: false,
            business_trip: true,
            gender: "MAN",
            age: 35,
            city: City.SHYMKENT,
            work_experience: [
                {
                    date_from: "2018-05-01",
                    date_to: "2022-12-31",
                    title: "Жүргізуші",
                    category: Category.TRANSPORT,
                    company: "Logistics Corp",
                    desc_experience: "Жүк көліктерін басқару және тауарларды жеткізу.",
                },
            ],
            education: [
                {
                    date_from: "2010-09-01",
                    place: "Шымкент колледжі",
                    professional: "Механика",
                },
            ],
            professional_skills: ["Жүк көлігін басқару", "Техникалық қызмет көрсету"],
            personal_skills: "Жауапкершілік, төзімділік, зейінділік.",
            lang: ["Қазақша", "Орысша"],
            category_drive_license: [CategoryDriveLicense.C, CategoryDriveLicense.B],
        },
    },
    {
        id: 4,
        title: "Графикалық дизайнер",
        slug: "graphic-designer",
        from_salary: 300000,
        to_salary: 500000,
        currency: Currency.KZT,
        work_experience: WorkExperience.ONE_TO_THREE_YEARS,
        date_publish: "2025-01-15",
        avatar: "mdi-account-circle-outline",
        education_level: EducationLevel.VOCATIONAL,
        category: Category.DESIGN,
        info_resume: {
            conditions: [EmploymentType.FREELANCE, WorkSchedule.FLEXIBLE],
            removal: true,
            business_trip: false,
            gender: "WOMEN",
            age: 28,
            city: City.AKTAU,
            work_experience: [
                {
                    date_from: "2021-01-01",
                    date_to: "2024-12-31",
                    title: "Графикалық дизайнер",
                    category: Category.DESIGN,
                    company: "Design Studio",
                    desc_experience: "Веб-сайттар және мобильді қосымшалар үшін дизайн жасау.",
                },
            ],
            education: [
                {
                    date_from: "2017-09-01",
                    place: "Дизайн және өнер колледжі",
                    professional: "Графикалық дизайн",
                },
            ],
            professional_skills: ["Adobe Photoshop", "Illustrator", "Figma"],
            personal_skills: "Шығармашылық, топпен жұмыс, қарым-қатынас.",
            lang: ["Қазақша", "Ағылшынша"],
            category_drive_license: [],
        },
    },
    {
        id: 5,
        title: "Бағдарламалық инженер",
        slug: "software-engineer",
        from_salary: 2500,
        to_salary: 4000,
        currency: Currency.EUR,
        work_experience: WorkExperience.FIVE_TO_SEVEN_YEARS,
        date_publish: "2025-01-14",
        avatar: "mdi-account-circle-outline",
        education_level: EducationLevel.HIGHER,
        category: Category.IT,
        info_resume: {
            conditions: [EmploymentType.FULL_TIME],
            removal: true,
            business_trip: true,
            gender: "MAN",
            age: 32,
            city: City.KARAGANDY,
            work_experience: [
                {
                    date_from: "2015-01-01",
                    date_to: "2024-12-31",
                    title: "Бағдарламалық инженер",
                    category: Category.IT,
                    company: "Code Innovators",
                    desc_experience: "Күрделі бағдарламалық шешімдерді әзірлеу және енгізу.",
                },
            ],
            education: [
                {
                    date_from: "2010-09-01",
                    place: "Қазақ техникалық университеті",
                    professional: "Бағдарламалық инженерия",
                },
            ],
            professional_skills: ["C++", "Python", "Алгоритмдер және деректер құрылымы"],
            personal_skills: "Жауапкершілік, аналитикалық ойлау, топтық жұмыс.",
            lang: ["Қазақша", "Ағылшынша"],
            category_drive_license: [CategoryDriveLicense.B],
        },
    },
    {
        id: 6,
        title: "Математика мұғалімі",
        slug: "mathematics-teacher",
        from_salary: 60000,
        to_salary: 90000,
        currency: Currency.RUB,
        work_experience: WorkExperience.ONE_TO_THREE_YEARS,
        date_publish: "2025-01-13",
        avatar: "mdi-account-circle-outline",
        education_level: EducationLevel.HIGHER,
        category: Category.EDUCATION,
        info_resume: {
            conditions: [EmploymentType.FULL_TIME, WorkSchedule.FREE],
            removal: false,
            business_trip: false,
            gender: "WOMEN",
            age: 30,
            city: City.TARAZ,
            work_experience: [
                {
                    date_from: "2020-01-01",
                    date_to: "2024-12-31",
                    title: "Математика мұғалімі",
                    category: Category.EDUCATION,
                    company: "№15 орта мектеп",
                    desc_experience: "Орта және жоғары сыныптарда математикадан сабақ беру.",
                },
            ],
            education: [
                {
                    date_from: "2015-09-01",
                    place: "Педагогикалық университет",
                    professional: "Математика пәнінің оқытушысы",
                },
            ],
            professional_skills: ["Оқыту", "Балалармен жұмыс", "Оқыту әдістемелері"],
            personal_skills: "Төзімділік, жауапкершілік, шығармашылық.",
            lang: ["Қазақша", "Орысша"],
            category_drive_license: [],
        },
    },
    {
        id: 7,
        title: "Бариста",
        slug: "barista",
        from_salary: 8,
        to_salary: 10,
        currency: Currency.USD,
        work_experience: WorkExperience.NO_EXPERIENCE,
        date_publish: "2025-01-12",
        avatar: "mdi-account-circle-outline",
        education_level: EducationLevel.NONE,
        category: Category.SERVICE,
        info_resume: {
            conditions: [EmploymentType.PART_TIME, WorkSchedule.SHIFT],
            removal: false,
            business_trip: false,
            gender: "MAN",
            age: 20,
            city: City.KOSTANAY,
            work_experience: [],
            education: [],
            professional_skills: ["Кофе дайындау", "Клиенттерге қызмет көрсету"],
            personal_skills: "Қарапайымдылық, топпен жұмыс, энергия.",
            lang: ["Қазақша"],
            category_drive_license: [],
        },
    },
    {
        id: 8,
        title: "Заңгер",
        slug: "lawyer",
        from_salary: 500000,
        to_salary: 700000,
        currency: Currency.KZT,
        work_experience: WorkExperience.THREE_TO_FIVE_YEARS,
        date_publish: "2025-01-11",
        avatar: "mdi-account-circle-outline",
        education_level: EducationLevel.MASTER,
        category: Category.LAW,
        info_resume: {
            conditions: [EmploymentType.FULL_TIME],
            removal: false,
            business_trip: true,
            gender: "MAN",
            age: 40,
            city: City.ASTANA,
            work_experience: [
                {
                    date_from: "2017-01-01",
                    date_to: "2024-12-31",
                    title: "Заңгер",
                    category: Category.LAW,
                    company: "Legal Consulting",
                    desc_experience: "Азаматтық істерді жүргізу және клиенттерді кеңес беру.",
                },
            ],
            education: [
                {
                    date_from: "2010-09-01",
                    place: "Құқық университеті",
                    professional: "Құқықтану",
                },
            ],
            professional_skills: ["Азаматтық құқық", "Кеңес беру", "Келісімшарт жасау"],
            personal_skills: "Зейін, тәртіп, ұйымдасушылық.",
            lang: ["Қазақша", "Орысша"],
            category_drive_license: [CategoryDriveLicense.B],
        },
    },
    {
        id: 9,
        title: "HR-менеджер",
        slug: "hr-manager",
        from_salary: 2000,
        to_salary: 3500,
        currency: Currency.EUR,
        work_experience: WorkExperience.ONE_TO_THREE_YEARS,
        date_publish: "2025-01-10",
        avatar: "mdi-account-circle-outline",
        education_level: EducationLevel.HIGHER,
        category: Category.HR,
        info_resume: {
            conditions: [EmploymentType.FULL_TIME],
            removal: true,
            business_trip: false,
            gender: "WOMEN",
            age: 29,
            city: City.PETROPAVLOVSK,
            work_experience: [
                {
                    date_from: "2021-01-01",
                    date_to: "2024-12-31",
                    title: "HR-менеджер",
                    category: Category.HR,
                    company: "Global HR Solutions",
                    desc_experience: "Қызметкерлерді іріктеу, тренингтер ұйымдастыру және бейімдеу.",
                },
            ],
            education: [
                {
                    date_from: "2016-09-01",
                    place: "Қазақстан менеджмент университеті",
                    professional: "Қызметкерлерді басқару",
                },
            ],
            professional_skills: ["Қызметкерлерді іріктеу", "Бейімдеу", "Іс-шаралар ұйымдастыру"],
            personal_skills: "Қарым-қатынас, жауапкершілік, энергия.",
            lang: ["Қазақша", "Орысша"],
            category_drive_license: [],
        },
    },
];

export const resume_kk: IResume[] = data;

