import type { IResume } from "~/types";
import {
    Category,
    CategoryDriveLicense,
    City,
    Currency,
    EducationLevel,
    EmploymentType,
    WorkSchedule
} from "~/types";

const data: IResume[] = [
    {
        id: 1,
        title: "Программист Frontend",
        slug: "frontend-developer",
        from_salary: 2000,
        to_salary: 3000,
        currency: Currency.USD,
        work_experience: "2 года",
        date_publish: "2025-01-18",
        avatar: "mdi-account-circle-outline",
        education_level: EducationLevel.HIGHER,
        category: Category.IT,
        info_resume: {
            conditions: [EmploymentType.FULL_TIME, WorkSchedule.REMOTE],
            removal: true,
            business_trip: false,
            gender: "MAN",
            age: 25,
            city: City.ALMATY,
            work_experience: [
                {
                    date_from: "2023-01-01",
                    date_to: "2024-12-31",
                    title: "Junior Frontend Developer",
                    category: Category.IT,
                    company: "Tech Solutions",
                    desc_experience: "Разработка интерфейсов с использованием Vue.js и TypeScript.",
                },
            ],
            education: [
                {
                    date_from: "2020-09-01",
                    place: "Казахский национальный университет",
                    professional: "Информационные технологии",
                },
            ],
            professional_skills: ["HTML", "CSS", "JavaScript", "Vue.js"],
            personal_skills: "Коммуникабельность, ответственность, креативность.",
            lang: ["Русский", "Английский"],
            category_drive_license: [CategoryDriveLicense.B],
        },
    },
    {
        id: 2,
        title: "Менеджер по продажам",
        slug: "sales-manager",
        from_salary: 350000,
        to_salary: null,
        currency: Currency.KZT,
        work_experience: "Без опыта",
        date_publish: "2025-01-17",
        avatar: "mdi-account-circle-outline",
        education_level: EducationLevel.SECONDARY,
        category: Category.SALES,
        info_resume: {
            conditions: [EmploymentType.PART_TIME],
            removal: false,
            business_trip: false,
            gender: "WOMEN",
            age: 22,
            city: City.ASTANA,
            work_experience: [],
            education: [
                {
                    date_from: "2019-09-01",
                    place: "Колледж экономики и сервиса",
                    professional: "Менеджмент",
                },
            ],
            professional_skills: ["Навыки продаж", "Переговоры", "Работа с клиентами"],
            personal_skills: "Коммуникабельность, целеустремленность, гибкость.",
            lang: ["Русский"],
            category_drive_license: [],
        },
    },
    {
        id: 3,
        title: "Водитель грузового автомобиля",
        slug: "truck-driver",
        from_salary: 70000,
        to_salary: 100000,
        currency: Currency.RUB,
        work_experience: "5 лет",
        date_publish: "2025-01-16",
        avatar: "mdi-account-circle-outline",
        education_level: EducationLevel.SECONDARY,
        category: Category.TRANSPORT,
        info_resume: {
            conditions: [EmploymentType.TEMPORARY, WorkSchedule.ROTATIONAL],
            removal: false,
            business_trip: true,
            gender: "MAN",
            age: 35,
            city: City.SHYMKENT,
            work_experience: [
                {
                    date_from: "2018-05-01",
                    date_to: "2022-12-31",
                    title: "Водитель",
                    category: Category.TRANSPORT,
                    company: "Logistics Corp",
                    desc_experience: "Управление грузовыми автомобилями и доставка товаров.",
                },
            ],
            education: [
                {
                    date_from: "2010-09-01",
                    place: "Шымкентский колледж",
                    professional: "Механика",
                },
            ],
            professional_skills: ["Управление грузовым транспортом", "Техническое обслуживание"],
            personal_skills: "Ответственность, стрессоустойчивость, внимательность.",
            lang: ["Русский", "Казахский"],
            category_drive_license: [CategoryDriveLicense.C, CategoryDriveLicense.B],
        },
    },
    {
        id: 4,
        title: "Графический дизайнер",
        slug: "graphic-designer",
        from_salary: 300000,
        to_salary: 500000,
        currency: Currency.KZT,
        work_experience: "3 года",
        date_publish: "2025-01-15",
        avatar: "mdi-account-circle-outline",
        education_level: EducationLevel.VOCATIONAL,
        category: Category.DESIGN,
        info_resume: {
            conditions: [EmploymentType.FREELANCE, WorkSchedule.FLEXIBLE],
            removal: true,
            business_trip: false,
            gender: "WOMEN",
            age: 28,
            city: City.AKTAU,
            work_experience: [
                {
                    date_from: "2021-01-01",
                    date_to: "2024-12-31",
                    title: "Графический дизайнер",
                    category: Category.DESIGN,
                    company: "Design Studio",
                    desc_experience: "Создание дизайнов для веб-сайтов и мобильных приложений.",
                },
            ],
            education: [
                {
                    date_from: "2017-09-01",
                    place: "Колледж дизайна и искусства",
                    professional: "Графический дизайн",
                },
            ],
            professional_skills: ["Adobe Photoshop", "Illustrator", "Figma"],
            personal_skills: "Креативность, работа в команде, коммуникабельность.",
            lang: ["Русский", "Английский"],
            category_drive_license: [],
        },
    },
    {
        id: 5,
        title: "Инженер-программист",
        slug: "software-engineer",
        from_salary: 2500,
        to_salary: 4000,
        currency: Currency.EUR,
        work_experience: "7 лет",
        date_publish: "2025-01-14",
        avatar: "mdi-account-circle-outline",
        education_level: EducationLevel.HIGHER,
        category: Category.IT,
        info_resume: {
            conditions: [EmploymentType.FULL_TIME],
            removal: true,
            business_trip: true,
            gender: "MAN",
            age: 32,
            city: City.KARAGANDY,
            work_experience: [
                {
                    date_from: "2015-01-01",
                    date_to: "2024-12-31",
                    title: "Инженер-программист",
                    category: Category.IT,
                    company: "Code Innovators",
                    desc_experience: "Разработка и внедрение сложных программных решений.",
                },
            ],
            education: [
                {
                    date_from: "2010-09-01",
                    place: "Казахский технический университет",
                    professional: "Программная инженерия",
                },
            ],
            professional_skills: ["C++", "Python", "Алгоритмы и структуры данных"],
            personal_skills: "Ответственность, аналитическое мышление, работа в команде.",
            lang: ["Русский", "Английский"],
            category_drive_license: [CategoryDriveLicense.B],
        },
    },
    {
        id: 6,
        title: "Учитель математики",
        slug: "mathematics-teacher",
        from_salary: 60000,
        to_salary: 90000,
        currency: Currency.RUB,
        work_experience: "4 года",
        date_publish: "2025-01-13",
        avatar: "mdi-account-circle-outline",
        education_level: EducationLevel.HIGHER,
        category: Category.EDUCATION,
        info_resume: {
            conditions: [EmploymentType.FULL_TIME, WorkSchedule.FREE],
            removal: false,
            business_trip: false,
            gender: "WOMEN",
            age: 30,
            city: City.TARAZ,
            work_experience: [
                {
                    date_from: "2020-01-01",
                    date_to: "2024-12-31",
                    title: "Учитель математики",
                    category: Category.EDUCATION,
                    company: "Средняя школа №15",
                    desc_experience: "Преподавание математики в средних и старших классах.",
                },
            ],
            education: [
                {
                    date_from: "2015-09-01",
                    place: "Педагогический университет",
                    professional: "Преподавание математики",
                },
            ],
            professional_skills: ["Преподавание", "Работа с детьми", "Методики обучения"],
            personal_skills: "Терпение, ответственность, креативность.",
            lang: ["Русский", "Казахский"],
            category_drive_license: [],
        },
    },
    {
        id: 7,
        title: "Бариста",
        slug: "barista",
        from_salary: 8,
        to_salary: 10,
        currency: Currency.USD,
        work_experience: "Без опыта",
        date_publish: "2025-01-12",
        avatar: "mdi-account-circle-outline",
        education_level: EducationLevel.NONE,
        category: Category.SERVICE,
        info_resume: {
            conditions: [EmploymentType.PART_TIME, WorkSchedule.SHIFT],
            removal: false,
            business_trip: false,
            gender: "MAN",
            age: 20,
            city: City.KOSTANAY,
            work_experience: [],
            education: [],
            professional_skills: ["Приготовление кофе", "Обслуживание клиентов"],
            personal_skills: "Доброжелательность, работа в команде, энергичность.",
            lang: ["Русский"],
            category_drive_license: [],
        },
    },
    {
        id: 8,
        title: "Юрист",
        slug: "lawyer",
        from_salary: 500000,
        to_salary: 700000,
        currency: Currency.KZT,
        work_experience: "5 лет",
        date_publish: "2025-01-11",
        avatar: "mdi-account-circle-outline",
        education_level: EducationLevel.MASTER,
        category: Category.LAW,
        info_resume: {
            conditions: [EmploymentType.FULL_TIME],
            removal: false,
            business_trip: true,
            gender: "MAN",
            age: 40,
            city: City.ASTANA,
            work_experience: [
                {
                    date_from: "2017-01-01",
                    date_to: "2024-12-31",
                    title: "Юрист",
                    category: Category.LAW,
                    company: "Legal Consulting",
                    desc_experience: "Ведение гражданских дел и консультирование клиентов.",
                },
            ],
            education: [
                {
                    date_from: "2010-09-01",
                    place: "Юридический университет",
                    professional: "Юриспруденция",
                },
            ],
            professional_skills: ["Гражданское право", "Консультации", "Договорная работа"],
            personal_skills: "Внимательность, организованность, дисциплинированность.",
            lang: ["Русский", "Английский"],
            category_drive_license: [CategoryDriveLicense.B],
        },
    },
    {
        id: 9,
        title: "HR-менеджер",
        slug: "hr-manager",
        from_salary: 2000,
        to_salary: 3500,
        currency: Currency.EUR,
        work_experience: "2 года",
        date_publish: "2025-01-10",
        avatar: "mdi-account-circle-outline",
        education_level: EducationLevel.HIGHER,
        category: Category.HR,
        info_resume: {
            conditions: [EmploymentType.FULL_TIME],
            removal: true,
            business_trip: false,
            gender: "WOMEN",
            age: 29,
            city: City.PETROPAVLOVSK,
            work_experience: [
                {
                    date_from: "2021-01-01",
                    date_to: "2024-12-31",
                    title: "HR-менеджер",
                    category: Category.HR,
                    company: "Global HR Solutions",
                    desc_experience: "Подбор персонала, организация тренингов и адаптация сотрудников.",
                },
            ],
            education: [
                {
                    date_from: "2016-09-01",
                    place: "Казахстанский университет менеджмента",
                    professional: "Управление персоналом",
                },
            ],
            professional_skills: ["Подбор персонала", "Адаптация сотрудников", "Организация мероприятий"],
            personal_skills: "Коммуникабельность, ответственность, энергичность.",
            lang: ["Русский", "Английский"],
            category_drive_license: [],
        },
    },
];

export const resume_ru: IResume[] = data