import type { IVacancy } from "~/types";
import {
    WorkSchedule,
    EducationLevel,
    EmploymentType,
    Category,
    City,
    Currency,
    WorkExperience,
} from "~/types";

const data: IVacancy[] = [
    {
        id: 1,
        slug: "frontend-developer",
        title: "Frontend бағдарламашы",
        post: "Frontend Developer",
        category: Category.IT,
        from_salary: 2000,
        to_salary: 3000,
        currency: Currency.USD,
        company: "Tech Solutions",
        date_publish: "2025-01-18",
        info_vacancy: {
            job_format: WorkSchedule.REMOTE,
            education: EducationLevel.HIGHER,
            type_employment: EmploymentType.FULL_TIME,
            internship: false,
            work_experience: WorkExperience.ONE_TO_THREE_YEARS,
        },
        professional_skills: ["HTML", "CSS", "JavaScript", "Vue.js"],
        personal_skills: ["Қарым-қатынас", "Жауапкершілік", "Шығармашылық"],
        address: `${City.ALMATY}, Абая көшесі, 50`,
    },
    {
        id: 2,
        slug: "sales-manager",
        title: "Сату менеджері",
        post: "Sales Manager",
        category: Category.SALES,
        from_salary: 350000,
        to_salary: null,
        currency: Currency.KZT,
        company: "Market Experts",
        date_publish: "2025-01-17",
        info_vacancy: {
            job_format: WorkSchedule.FULL_TIME,
            education: EducationLevel.SECONDARY,
            type_employment: EmploymentType.PART_TIME,
            internship: false,
            work_experience: WorkExperience.NO_EXPERIENCE,
        },
        professional_skills: ["Сату дағдылары", "Келіссөздер", "Клиенттермен жұмыс"],
        personal_skills: ["Мақсатқа ұмтылушылық", "Икемділік", "Топта жұмыс істеу"],
        address: `${City.ASTANA}, Достық көшесі, 10`,
    },
    {
        id: 3,
        slug: "truck-driver",
        title: "Жүк көлігінің жүргізушісі",
        post: "Truck Driver",
        category: Category.TRANSPORT,
        from_salary: 70000,
        to_salary: 100000,
        currency: Currency.RUB,
        company: "Logistics Corp",
        date_publish: "2025-01-16",
        info_vacancy: {
            job_format: WorkSchedule.ROTATIONAL,
            education: EducationLevel.SECONDARY,
            type_employment: EmploymentType.TEMPORARY,
            internship: false,
            work_experience: WorkExperience.THREE_TO_FIVE_YEARS,
        },
        professional_skills: ["Жүк көлігін басқару", "Жөндеу жұмыстары"],
        personal_skills: ["Назар аудару", "Жауапкершілік", "Қысымға төзімділік"],
        address: `${City.SHYMKENT}, Байтурсынов көшесі, 25`,
    },
    {
        id: 4,
        slug: "software-engineer",
        title: "Бағдарламалық жасақтама инженері",
        post: "Software Engineer",
        category: Category.IT,
        from_salary: 2500,
        to_salary: 4000,
        currency: Currency.EUR,
        company: "Code Innovators",
        date_publish: "2025-01-15",
        info_vacancy: {
            job_format: WorkSchedule.FULL_TIME,
            education: EducationLevel.HIGHER,
            type_employment: EmploymentType.FULL_TIME,
            internship: false,
            work_experience: WorkExperience.FIVE_TO_SEVEN_YEARS,
        },
        professional_skills: ["C++", "Python", "Деректер құрылымдары"],
        personal_skills: ["Аналитикалық ойлау", "Жауапкершілік", "Топтық жұмыс"],
        address: `${City.KARAGANDY}, Қазыбек би көшесі, 17`,
    },
    {
        id: 5,
        slug: "graphic-designer",
        title: "Графикалық дизайнер",
        post: "Graphic Designer",
        category: Category.DESIGN,
        from_salary: 300000,
        to_salary: 500000,
        currency: Currency.KZT,
        company: "Design Studio",
        date_publish: "2025-01-14",
        info_vacancy: {
            job_format: WorkSchedule.FLEXIBLE,
            education: EducationLevel.VOCATIONAL,
            type_employment: EmploymentType.FREELANCE,
            internship: false,
            work_experience: WorkExperience.ONE_TO_THREE_YEARS,
        },
        professional_skills: ["Adobe Photoshop", "Illustrator", "Figma"],
        personal_skills: ["Шығармашылық", "Топта жұмыс", "Қарым-қатынас"],
        address: `${City.AKTAU}, Тәуелсіздік көшесі, 12`,
    },
    {
        id: 6,
        slug: "mathematics-teacher",
        title: "Математика пәнінің мұғалімі",
        post: "Mathematics Teacher",
        category: Category.EDUCATION,
        from_salary: 60000,
        to_salary: 90000,
        currency: Currency.RUB,
        company: "Education Hub",
        date_publish: "2025-01-13",
        info_vacancy: {
            job_format: WorkSchedule.FULL_TIME,
            education: EducationLevel.HIGHER,
            type_employment: EmploymentType.FULL_TIME,
            internship: false,
            work_experience: WorkExperience.ONE_TO_THREE_YEARS,
        },
        professional_skills: ["Оқыту", "Балалармен жұмыс", "Оқыту әдістері"],
        personal_skills: ["Төзімділік", "Қарым-қатынас", "Жауапкершілік"],
        address: `${City.TARAZ}, Төле би көшесі, 18`,
    },
    {
        id: 7,
        slug: "barista",
        title: "Бариста",
        post: "Barista",
        category: Category.SERVICE,
        from_salary: 8,
        to_salary: 10,
        currency: Currency.USD,
        company: "Coffee Lovers",
        date_publish: "2025-01-12",
        info_vacancy: {
            job_format: WorkSchedule.PART_TIME,
            education: EducationLevel.NONE,
            type_employment: EmploymentType.PART_TIME,
            internship: false,
            work_experience: WorkExperience.NO_EXPERIENCE,
        },
        professional_skills: ["Кофе дайындау", "Клиенттерге қызмет көрсету"],
        personal_skills: ["Ізгі ниеттілік", "Топтық жұмыс", "Энергия"],
        address: `${City.KOSTANAY}, Абылайхан көшесі, 7`,
    },
    {
        id: 8,
        slug: "lawyer",
        title: "Заңгер",
        post: "Lawyer",
        category: Category.LAW,
        from_salary: 500000,
        to_salary: 700000,
        currency: Currency.KZT,
        company: "Legal Aid Co.",
        date_publish: "2025-01-11",
        info_vacancy: {
            job_format: WorkSchedule.FULL_TIME,
            education: EducationLevel.MASTER,
            type_employment: EmploymentType.FULL_TIME,
            internship: false,
            work_experience: WorkExperience.THREE_TO_FIVE_YEARS,
        },
        professional_skills: ["Азаматтық құқық", "Келісім-шарт жасау"],
        personal_skills: ["Ұқыптылық", "Тәртіптілік"],
        address: `${City.ASTANA}, Иманов көшесі, 5`,
    },
    {
        id: 9,
        slug: "hr-manager",
        title: "HR менеджері",
        post: "HR Manager",
        category: Category.HR,
        from_salary: 2000,
        to_salary: 3500,
        currency: Currency.EUR,
        company: "Talent Seekers",
        date_publish: "2025-01-10",
        info_vacancy: {
            job_format: WorkSchedule.FULL_TIME,
            education: EducationLevel.HIGHER,
            type_employment: EmploymentType.FULL_TIME,
            internship: false,
            work_experience: WorkExperience.ONE_TO_THREE_YEARS,
        },
        professional_skills: ["Қызметкерлерді таңдау", "Адаптация", "Ұйымдастыру"],
        personal_skills: ["Қарым-қатынас", "Жауапкершілік"],
        address: `${City.PETROPAVLOVSK}, Ленин көшесі, 10`,
    },
];

export const vacancy_kk: IVacancy[] = data;
